// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHA85aaCWKL6Qy7oGdD2QdIodlBRfCHHI',
    appId: '1:484376729633:web:12a260d704152790c42b60',
    messagingSenderId: '484376729633',
    projectId: 'e-commerce-app0',
    authDomain: 'e-commerce-app0.firebaseapp.com',
    storageBucket: 'e-commerce-app0.firebasestorage.app',
    measurementId: 'G-JK0JNZN9J0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM9JS9oHWbqTVirD_jN89BveASe5d6WJI',
    appId: '1:484376729633:android:373afcd69e96e5b4c42b60',
    messagingSenderId: '484376729633',
    projectId: 'e-commerce-app0',
    storageBucket: 'e-commerce-app0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfCMx6dEP2Jew1xSKKxCzaE6zi_Tv3ceY',
    appId: '1:484376729633:ios:d4ec5302b1e83e11c42b60',
    messagingSenderId: '484376729633',
    projectId: 'e-commerce-app0',
    storageBucket: 'e-commerce-app0.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfCMx6dEP2Jew1xSKKxCzaE6zi_Tv3ceY',
    appId: '1:484376729633:ios:d4ec5302b1e83e11c42b60',
    messagingSenderId: '484376729633',
    projectId: 'e-commerce-app0',
    storageBucket: 'e-commerce-app0.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHA85aaCWKL6Qy7oGdD2QdIodlBRfCHHI',
    appId: '1:484376729633:web:fffdfa8c060015b9c42b60',
    messagingSenderId: '484376729633',
    projectId: 'e-commerce-app0',
    authDomain: 'e-commerce-app0.firebaseapp.com',
    storageBucket: 'e-commerce-app0.firebasestorage.app',
    measurementId: 'G-28PDYF2EZB',
  );
}
